title: "Your Name"
email: your.email@example.com
description: >-
  Academic CV, portfolio & blog.
url: "https://username.github.io"
baseurl: "" # keep empty for username.github.io root
markdown: kramdown
permalink: /:title/
theme: null
plugins:
  - jekyll-seo-tag
