title: "Liffrey"
description: "Researcher · Developer · Portfolio"
markdown: kramdown
permalink: pretty        # nice /about/ style URLs
theme: null              # we’ll use our own CSS

# ❶ Define the collection
collections:
  portfolio:
    output: true                 # build HTML for each item
    permalink: /portfolio/:name/ # clean directory URL
