title: "Liffrey"
description: "Researcher · Developer · Portfolio"
baseurl: ""            # <username>.github.io kökü
markdown: kramdown
permalink: pretty

collections:
  portfolio:
    output: true
    permalink: /portfolio/:name/