title: "Liffrey"
description: "Portfolio & CV"
theme: null           # we’ll use our own CSS
markdown: kramdown
permalink: pretty

collections:
  portfolio:
    output: true
    permalink: /portfolio/:name/   # ← ekleyin